### PR TITLE
New way to create light entity

### PR DESCRIPTION
**Pull request by Garfonso**
With this PR I propose a different way to handle the light entity creation. It is much more modular than what I found before. 
You can now create a light entity with the following attributes:

- on / off (mandatoriy)
- dimmer
- color temperature
- hue/saturation color

Also auto creation from devices now does not seem to fail for light entities, at least for mine. I'd be really happy about more testing.

The old code for the dimmer is still in there. I still do not truly understand why it looks for completely different controls. So I'd leave it in there for now. Maybe we can get rid of the _parseCommandDimmer function and use the more generic _parseLightOn (and much simpler) function (I do not truly understand the edge cases the _parseCommandDimmer function handles, though, so I'd be happy about testing from people who know here, too).

This PR deprecates my other PR #66 

I'd be happy about feedback.
I might look into RGB string support. Not sure if that is easy / possible.

### CODE REVIEW

**Comment by Garfonso** [comment]
ok, implemented support "rgbSingle", i.e. rgb string in form of #00ff00. Both in same file produced some issues, because solely "hue" control was left over (why is this not added to rbgSignle type but saturation is?). But I managed to handle them. 
It is a bit counter intuitive, that _processCommon already adds the entity... maybe that should get reworked. But I was not 100% as of what all the entity and object id mapping really does.

**Comment by Garfonso** [comment]
Ok, I found a solution for many issues and there are two or three testers in the forum that reported it works now with a range of devices (hue, zigbee, shelly). I updated the PR accordingly. It is now much more cleaned up than before and all light features (I found) are implemented.

**Comment by Apollon77** [comment]
Cool. Thank you

**Comment by GermanBluefox** [comment]
Thank you

**Pull request merged**
