### PR TITLE
Additional fields to recognize added

### PR DESCRIPTION
**Pull request by algar42**
Added sunrise/sunset state detection and state_desc as a textual description of current weather condition.
These states are available in Accuweather adapter.

### CODE REVIEW

**Comment by Garfonso** [comment]
Thanks for the PR.

Since type-detector now adds the STATE to weatherForecast, I thought about setting this as state if lovelace supports the state (i.e. it is in this list:  https://github.com/home-assistant/frontend/blob/dev/src/data/weather.ts#L43 ).
Do this states match what accuweather writes there? Would it then make sense for your extended card to use the mdi icons or even the [animated icons from bramtkragen](https://github.com/bramkragten/weather-card/tree/master/dist/icons)?

ioBroker hacks the default weather card to show the icon if the state is an URL. If not, lovelace will show its icon for it. So this would work fine for the default weather card. What do you think about this?
I do not really like to add a state_descr attribute to the entity, because state should already be the description in HASS world.

**Comment by algar42** [comment]
Icons are not a big problem. We can add icon URL as the icon_url attribute to the entity, like it is already done for daily forecasts.x. 
The problem is that as far as I can see HASS uses 'state' as a icon url, and it is fine for current standard card, but the custom card needs to have yet another state for a textual weather description, e.g. 'Cloudy', 'Rainy' etc.  
I don't like the idea of trying to map the SVG icon name to the weather description like it is done in HASS, because a) Accuweather natively supports several languages and we don't need to carry about translations, b) it looks like the accuweather provides a little bit more descriptions than the number of icons it has :) 
I can update custom card to use any attributes from the entity as a text description - do you have a better solution for a weather description, instead of state_desc? Actually, why not the state_desc? If this field is not required in entity by any other cards it will be just ignored, similar to the sunrise and sunset values. 
Currently both the native HASS weather card and my custom one works fine....

**Comment by Garfonso** [comment]
> 
> 
> Icons are not a big problem. We can add icon URL as the icon_url attribute to the entity, like it is already done for daily forecasts.x.
> The problem is that as far as I can see HASS uses 'state' as a icon url, and it is fine for current standard card, but the custom card needs to have yet another state for a textual weather description, e.g. 'Cloudy', 'Rainy' etc.

No, we change the weather card to support icon url in state. Usually state is one of  those strings:
"clear-night", "cloudy", "exceptional", "fog", "hail", "lightning", "lightning-rainy", "partlycloudy", "pouring", "rainy", "snowy", "snowy-rainy", "sunny", "windy", "windy-variant".

I did hack the frontend to support icon url here:
https://github.com/Garfonso/home-assistant-polymer/blob/iob/src/data/weather.ts#L446 
and here
https://github.com/Garfonso/home-assistant-polymer/blob/iob/src/data/weather.ts#L420 
(and some more places). 
So it tests the value in state and if it contains some image ending (like jpg, png or so) it will just display the icon. Otherwise lovelace will try to select an icon, which will only work for the strings above.

> I don't like the idea of trying to map the SVG icon name to the weather description like it is done in HASS, because a) Accuweather natively supports several languages and we don't need to carry about translations, b) it looks like the accuweather provides a little bit more descriptions than the number of icons it has :)
> I can update custom card to use any attributes from the entity as a text description - do you have a better solution for a weather description, instead of state_desc? Actually, why not the state_desc? If this field is not required in entity by any other cards it will be just ignored, similar to the sunrise and sunset values.
> Currently both the native HASS weather card and my custom one works fine....

additional attributes that are not recognized by lovelace are displayed on the more-info dialog, usually. Might not be the case for weather.

Ok, let's use it as is, for now.

**Comment by algar42** [comment]
> additional attributes that are not recognized by lovelace are displayed on the more-info dialog, usually. Might not be the case for weather.
No, it is not the case. Both cards displays the standard HASS more-info that does not include any non-native attributes. So, I think it should work ok for now, at least until we found more general and more correct solution :)

**Comment by GermanBluefox** [comment]
@Garfonso What should we do with this PR?

**Comment by Garfonso** [comment]
@GermanBluefox please merge. Sunrise & Sunset are good.
State is not perfect, but ok for now.

**Comment by algar42** [comment]
can this be merged? :)

**Comment by Garfonso** [comment]
uhm... changing the IDs is potentially a breaking change. ;-) 

But it's ok with me.

**Comment by algar42** [comment]
IDs that contain Russian text does not work anyway, so I think we do not break anything dramatically :)

**Comment by Garfonso** [comment]
Yes, the russion part is of not so much the problem. But replacing multiple _ with one _ might create issues for some people. But I'd still say this is a good change.

**Comment by algar42** [comment]
I can remove dash replacement if you think it can make some troubles. Do you know when repeating dashes could appear in ID except for having repeating spaces in device name?

**Pull request merged**
