### PR TITLE
new test version

### PR DESCRIPTION
**Pull request by Garfonso**
### 1.2.5 (2020-07-10)
* (Garfonso) Fixed: Parse initial values the same way as state changes
* (Garfonso) Added: Work around for (old) common.states of type string

### CODE REVIEW

**Comment by Apollon77** [comment]
Ready?

**Comment by Garfonso** [comment]
yes,

**Comment by Apollon77** [comment]
Thank you!

**Comment by Apollon77** [comment]
Do you do release?

**Comment by Garfonso** [comment]
No, there is a bug with the code editor which I could not solve, yet... somehow cursor placement is off until scrollbars where visible at least once. I'm not sure, why. Maybe @GermanBluefox or somebody else who knows a bit more about frontend could have a look?

**Pull request merged**
