### PR TITLE
build lovelace v 20190918.0

### PR DESCRIPTION
**Pull request by Scrounger**
@GermanBluefox 
compiled actual lovelace version 20190918.0

The auto login not work anymore, but i can figure our where the problem is. So thats on your site please.

### CODE REVIEW

**Comment by GermanBluefox** [comment]
Hm.. Where have you got the home-assistant-polymer repo?
Because I modified a bit the dev branch, because notifications were moved out of lovelace.
I merged yesterday the latest dev and want to create today evening one version for ioBroker.

Is the error with "auto login" fixed on the latest dev home-assistant-polymer?

**Comment by Scrounger** [comment]
I used the [build.bat](https://github.com/ioBroker/ioBroker.lovelace/blob/f2fc390751c6a9e4ca23d7f87f334298579e696f/build/build.bat) from the repo.

The old script grabs master from https://github.com/home-assistant/home-assistant-polymer.
With this version notification works like it should.

**Comment by GermanBluefox** [comment]
I prepered yesterday the version.
Does it work by you? From git

**Comment by Scrounger** [comment]
Yes it works, thanks!

**Pull request closed without merging**
