### PR TITLE
allow to restrict auto created entities to alias.0.*

### PR DESCRIPTION
**Pull request by Garfonso**
A lot of adapters create / change / delete objects regularly. This leads to a lot of entity-recreation in lovelace.
Also some adapters "create" devices by themselves (i.e. adding states to rooms + functions).

In order to have a "clean" device-system I prefer to use only devices I created myself in alias.0.

So I added the option to do this.

BTW: Some translations in the config read as if automatically translated. If there is such a tool, then I did not understand how to use it. In either case, I was not able to add translations for the new checkbox-label for most languages. :-/

### CODE REVIEW

**Comment by GermanBluefox** [comment]
Thank you. Can you update the versions and news too? So I can faster publish the new version

**Comment by Garfonso** [comment]
Sure I can do that.

**Comment by Garfonso** [comment]
Ah, one question regarding that: How do you translate the lift of changes in all these languages?

BTW:
I noticed a restriction with that change. Manual entities can still be created for all objects (which is fine, I think). But when changing the setting for a object for lovelace.x outside of alias.0.*, the instance will not handle the change from what I see and requires a restart to reflect the changes.
I did not yet 100% understand how these settings work, but probably a subscription to * is still necessary for that case and should then call _processManualEntity on that object, right?

**Comment by Apollon77** [comment]
https://translator.iobroker.in/ is your friend

**Pull request merged**
